In [48]:
print("Started learning pandas Journey!!")

Started learning pandas Journey!!

In [2]:
print("Hello Aman!")

Hello Aman!

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame([1,2,3,4,5,6],columns=['Col_table'])

In [9]:
print(df)

   Col_table
0          1
1          2
2          3
3          4
4          5
5          6

In [10]:
print(type(df))

<class 'pandas.DataFrame'>

In [11]:
data = {
    'Name' : ['Aman', 'Atul', 'Ayan', 'Mk'],
    'Age' : [21,22,23,23],
    'salary' : [150000,21000,54322,42111]
}

In [12]:
df = pd.DataFrame(data)
print(df)

   Name  Age  salary
0  Aman   21  150000
1  Atul   22   21000
2  Ayan   23   54322
3    Mk   23   42111

In [17]:
print(type(df))

<class 'pandas.DataFrame'>

In [18]:
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [19]:
df.head() # shows all data

   Name  Age  salary
0  Aman   21  150000
1  Atul   22   21000
2  Ayan   23   54322
3    Mk   23   42111

In [20]:
df.head(2) #shows only top rows

   Name  Age  salary
0  Aman   21  150000
1  Atul   22   21000

In [21]:
df.tail()

   Name  Age  salary
0  Aman   21  150000
1  Atul   22   21000
2  Ayan   23   54322
3    Mk   23   42111

In [22]:
df.tail(2) # display last records

   Name  Age  salary
2  Ayan   23   54322
3    Mk   23   42111

In [24]:
df.shape

(4, 3)

In [25]:
df.columns

Index(['Name', 'Age', 'salary'], dtype='str')

In [34]:
df.rename(columns={'salary':'monthly salary'}, inplace=True) # replace column name

In [35]:
print(df)

   Name  Age  monthly salary
0  Aman   21          150000
1  Atul   22           21000
2  Ayan   23           54322
3    Mk   23           42111

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   monthly salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [39]:
df.describe()

             Age  monthly salary
count   4.000000        4.000000
mean   22.250000    66858.250000
std     0.957427    57111.334639
min    21.000000    21000.000000
25%    21.750000    36833.250000
50%    22.500000    48216.500000
75%    23.000000    78241.500000
max    23.000000   150000.000000

In [40]:
  pd# sava and load data from csv

In [40]:
  pd# sava and load data from csv

In [41]:
df

   Name  Age  monthly salary
0  Aman   21          150000
1  Atul   22           21000
2  Ayan   23           54322
3    Mk   23           42111

In [44]:
df.to_csv('data_test.csv',index=False) # export data fram

In [45]:
load_data = pd.read_csv('data_test.csv') #import data frame

In [46]:
load_data

   Name  Age  monthly salary
0  Aman   21          150000
1  Atul   22           21000
2  Ayan   23           54322
3    Mk   23           42000

In [ ]:
# rows and column selection

In [49]:
df

   Name  Age  monthly salary
0  Aman   21          150000
1  Atul   22           21000
2  Ayan   23           54322
3    Mk   23           42111

In [50]:
#select column
df[['Name']]  #single column

   Name
0  Aman
1  Atul
2  Ayan
3    Mk

In [51]:
df[['Name','monthly salary']] #multiple column

   Name  monthly salary
0  Aman          150000
1  Atul           21000
2  Ayan           54322
3    Mk           42111

In [53]:
# loc - label based index
df.loc[df.Name=='Atul']  # Selecting Rows

   Name  Age  monthly salary
1  Atul   22           21000

In [57]:
# iloc - index-value based
df.iloc[0]

Name                Aman
Age                   21
monthly salary    150000
Name: 0, dtype: object

In [59]:
df.iloc[0:2]

   Name  Age  monthly salary
0  Aman   21          150000
1  Atul   22           21000

In [61]:
df[df['Age']>=22]

   Name  Age  monthly salary
1  Atul   22           21000
2  Ayan   23           54322
3    Mk   23           42111

In [62]:
df[(df['Age']>=22)&(df['monthly salary']>=30000)]

   Name  Age  monthly salary
2  Ayan   23           54322
3    Mk   23           42111

In [64]:
df.where((df['Age']>=22)&(df['monthly salary']>=30000))

   Name   Age  monthly salary
0   NaN   NaN             NaN
1   NaN   NaN             NaN
2  Ayan  23.0         54322.0
3    Mk  23.0         42111.0

In [65]:
df.where((df['Age']>=22)&(df['monthly salary']>=30000),other='Not Eligible')

           Name           Age monthly salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2          Ayan            23          54322
3            Mk            23          42111

In [ ]:
# Rows and columns Operations

In [13]:
# ADD New Column
df['Position']=["CEO","HR","CTO","SDE"]

In [14]:
df

   Name  Age  salary Position
0  Aman   21  150000      CEO
1  Atul   22   21000       HR
2  Ayan   23   54322      CTO
3    Mk   23   42111      SDE

In [15]:
df['Bonus'] = df['salary'] * 0.20

In [16]:
df

   Name  Age  salary Position    Bonus
0  Aman   21  150000      CEO  30000.0
1  Atul   22   21000       HR   4200.0
2  Ayan   23   54322      CTO  10864.4
3    Mk   23   42111      SDE   8422.2

In [17]:
# Add New Row
df.loc[len(df)] = ["Sumit",23,200000,"MR",40000]

In [18]:
df

    Name  Age  salary Position    Bonus
0   Aman   21  150000      CEO  30000.0
1   Atul   22   21000       HR   4200.0
2   Ayan   23   54322      CTO  10864.4
3     Mk   23   42111      SDE   8422.2
4  Sumit   23  200000       MR  40000.0

In [73]:
len(df)

5

In [74]:
# update value - using index value 
df.loc[0,'monthly salary'] = 120000

In [75]:
df

    Name  Age  monthly salary Position    Bonus
0   Aman   21          120000      CEO  30000.0
1   Atul   22           21000       HR   4200.0
2   Ayan   23           54322      CTO  10864.4
3     Mk   23           42111      SDE   8422.2
4  Sumit   23          200000       MR  40000.0

In [85]:
df.loc[df.Name=="Aman","monthly salary"] = 130000

In [86]:
df

    Name  Age  monthly salary Position    Bonus    salary
0   Aman   21          130000      CEO  30000.0  130000.0
1   Atul   22           21000       HR   4200.0       NaN
2   Ayan   23           54322      CTO  10864.4       NaN
3     Mk   23           42111      SDE   8422.2       NaN
4  Sumit   23          200000       MR  40000.0       NaN

In [ ]:
#Delete Values - Row and Columns Values

In [89]:
df.drop(df[df.Name == "Sumit"].index)  # delete row axis = 0

   Name  Age  monthly salary Position    Bonus    salary
0  Aman   21          130000      CEO  30000.0  130000.0
1  Atul   22           21000       HR   4200.0       NaN
2  Ayan   23           54322      CTO  10864.4       NaN
3    Mk   23           42111      SDE   8422.2       NaN

In [91]:
df.drop("salary", axis=1)

    Name  Age  monthly salary Position    Bonus
0   Aman   21          130000      CEO  30000.0
1   Atul   22           21000       HR   4200.0
2   Ayan   23           54322      CTO  10864.4
3     Mk   23           42111      SDE   8422.2
4  Sumit   23          200000       MR  40000.0

In [92]:
df

    Name  Age  monthly salary Position    Bonus    salary
0   Aman   21          130000      CEO  30000.0  130000.0
1   Atul   22           21000       HR   4200.0       NaN
2   Ayan   23           54322      CTO  10864.4       NaN
3     Mk   23           42111      SDE   8422.2       NaN
4  Sumit   23          200000       MR  40000.0       NaN

In [93]:
df.drop("salary", axis=1, inplace=True)

In [94]:
df

    Name  Age  monthly salary Position    Bonus
0   Aman   21          130000      CEO  30000.0
1   Atul   22           21000       HR   4200.0
2   Ayan   23           54322      CTO  10864.4
3     Mk   23           42111      SDE   8422.2
4  Sumit   23          200000       MR  40000.0

In [ ]:
# Sort Table

In [99]:
df.rename(columns={'monthly salary' : 'Salary'},inplace=True) # Rename column name for simplicity

In [100]:
df

    Name  Age  Salary Position    Bonus
0   Aman   21  130000      CEO  30000.0
1   Atul   22   21000       HR   4200.0
2   Ayan   23   54322      CTO  10864.4
3     Mk   23   42111      SDE   8422.2
4  Sumit   23  200000       MR  40000.0

In [101]:
df.sort_values('Salary', ascending=False)

    Name  Age  Salary Position    Bonus
4  Sumit   23  200000       MR  40000.0
0   Aman   21  130000      CEO  30000.0
2   Ayan   23   54322      CTO  10864.4
3     Mk   23   42111      SDE   8422.2
1   Atul   22   21000       HR   4200.0

In [102]:
df.sort_values('Salary') # by default ascending order

    Name  Age  Salary Position    Bonus
1   Atul   22   21000       HR   4200.0
3     Mk   23   42111      SDE   8422.2
2   Ayan   23   54322      CTO  10864.4
0   Aman   21  130000      CEO  30000.0
4  Sumit   23  200000       MR  40000.0

In [38]:
df['DOJ'] = ["2024-04-15","2024-04-01","2024-04-23","2024-04-25", "2025-04-12"]

In [39]:
df

   Name   Age    salary Position    Bonus         DOJ
0  Aman  21.0  150000.0      CEO  30000.0  2024-04-15
1  Atul  22.0   21000.0       HR   4200.0  2024-04-01
2  Ayan  23.0   54322.0      CTO  10864.4  2024-04-23
3    Mk  23.0   42111.0      SDE   8422.2  2024-04-25
4   NaN   NaN       NaN      NaN      NaN  2025-04-12

In [124]:
print(type('DOJ'))

<class 'str'>

In [125]:
df['DOJ'].dtype

In [138]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [139]:
df['DOJ'].dtype

dtype('<M8[us]')

In [140]:
df1 = df

In [141]:
df1

    Name  Age  salary Position    Bonus        DOJ
0   Aman   21  150000      CEO  30000.0 2024-04-15
1   Atul   22   21000       HR   4200.0 2024-04-01
2   Ayan   23   54322      CTO  10864.4 2024-04-23
3     Mk   23   42111      SDE   8422.2 2024-04-25
4  Sumit   23  200000       MR  40000.0 2025-04-12

In [143]:
df1['DOJ2'] =   ["2024-04-15","2024-04-01","2024-04-23","2024-04-25", "2025-04-12"]

In [144]:
df1

    Name  Age  salary Position    Bonus        DOJ        DOJ2
0   Aman   21  150000      CEO  30000.0 2024-04-15  2024-04-15
1   Atul   22   21000       HR   4200.0 2024-04-01  2024-04-01
2   Ayan   23   54322      CTO  10864.4 2024-04-23  2024-04-23
3     Mk   23   42111      SDE   8422.2 2024-04-25  2024-04-25
4  Sumit   23  200000       MR  40000.0 2025-04-12  2025-04-12

In [148]:
df1['DOJ2'] = pd.to_datetime(df['DOJ2'],format = '%Y-%m-%d')

In [149]:
df1

    Name  Age  salary Position    Bonus        DOJ       DOJ2
0   Aman   21  150000      CEO  30000.0 2024-04-15 2024-04-15
1   Atul   22   21000       HR   4200.0 2024-04-01 2024-04-01
2   Ayan   23   54322      CTO  10864.4 2024-04-23 2024-04-23
3     Mk   23   42111      SDE   8422.2 2024-04-25 2024-04-25
4  Sumit   23  200000       MR  40000.0 2025-04-12 2025-04-12

In [150]:
df1['DOJ2'].dtype

dtype('<M8[us]')

In [155]:
# Extract year, month, week, day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2     Tuesday
3    Thursday
4    Saturday
Name: DOJ, dtype: str

In [156]:
df['Month'] = df['DOJ'].dt.month_name()

In [157]:
df

    Name  Age  salary Position    Bonus        DOJ       DOJ2  Month
0   Aman   21  150000      CEO  30000.0 2024-04-15 2024-04-15  April
1   Atul   22   21000       HR   4200.0 2024-04-01 2024-04-01  April
2   Ayan   23   54322      CTO  10864.4 2024-04-23 2024-04-23  April
3     Mk   23   42111      SDE   8422.2 2024-04-25 2024-04-25  April
4  Sumit   23  200000       MR  40000.0 2025-04-12 2025-04-12  April

In [158]:
df['DOJ'] + pd.Timedelta(days=90)

0   2024-07-14
1   2024-06-30
2   2024-07-22
3   2024-07-24
4   2025-07-11
Name: DOJ, dtype: datetime64[us]

In [19]:
df.isnull() # handling null values

    Name    Age  salary  Position  Bonus
0  False  False   False     False  False
1  False  False   False     False  False
2  False  False   False     False  False
3  False  False   False     False  False
4  False  False   False     False  False

In [20]:
df

    Name  Age  salary Position    Bonus
0   Aman   21  150000      CEO  30000.0
1   Atul   22   21000       HR   4200.0
2   Ayan   23   54322      CTO  10864.4
3     Mk   23   42111      SDE   8422.2
4  Sumit   23  200000       MR  40000.0

In [21]:
import numpy as np

In [22]:
df.loc[df.Name=='Sumit']=np.nan

In [23]:
df

   Name   Age    salary Position    Bonus
0  Aman  21.0  150000.0      CEO  30000.0
1  Atul  22.0   21000.0       HR   4200.0
2  Ayan  23.0   54322.0      CTO  10864.4
3    Mk  23.0   42111.0      SDE   8422.2
4   NaN   NaN       NaN      NaN      NaN

In [24]:
df.fillna(0)

   Name   Age    salary Position    Bonus
0  Aman  21.0  150000.0      CEO  30000.0
1  Atul  22.0   21000.0       HR   4200.0
2  Ayan  23.0   54322.0      CTO  10864.4
3    Mk  23.0   42111.0      SDE   8422.2
4     0   0.0       0.0        0      0.0

In [25]:
df.isnull

<bound method DataFrame.isnull of    Name   Age    salary Position    Bonus
0  Aman  21.0  150000.0      CEO  30000.0
1  Atul  22.0   21000.0       HR   4200.0
2  Ayan  23.0   54322.0      CTO  10864.4
3    Mk  23.0   42111.0      SDE   8422.2
4   NaN   NaN       NaN      NaN      NaN>

In [29]:
df.isnull().sum()

Name        1
Age         1
salary      1
Position    1
Bonus       1
dtype: int64

In [ ]:
# Aggregation and Group by

In [30]:
df

   Name   Age    salary Position    Bonus
0  Aman  21.0  150000.0      CEO  30000.0
1  Atul  22.0   21000.0       HR   4200.0
2  Ayan  23.0   54322.0      CTO  10864.4
3    Mk  23.0   42111.0      SDE   8422.2
4   NaN   NaN       NaN      NaN      NaN

In [31]:
df.drop(4)

   Name   Age    salary Position    Bonus
0  Aman  21.0  150000.0      CEO  30000.0
1  Atul  22.0   21000.0       HR   4200.0
2  Ayan  23.0   54322.0      CTO  10864.4
3    Mk  23.0   42111.0      SDE   8422.2

In [33]:
df['Position'].value_counts()

Position
CEO    1
HR     1
CTO    1
SDE    1
Name: count, dtype: int64

In [37]:
df[df['Age']>=20].value_counts()

Name  Age   salary    Position  Bonus
Aman  21.0  150000.0  CEO       30000.0    1
Atul  22.0  21000.0   HR        4200.0     1
Ayan  23.0  54322.0   CTO       10864.4    1
Mk    23.0  42111.0   SDE       8422.2     1
Name: count, dtype: int64

In [40]:
df

   Name   Age    salary Position    Bonus         DOJ
0  Aman  21.0  150000.0      CEO  30000.0  2024-04-15
1  Atul  22.0   21000.0       HR   4200.0  2024-04-01
2  Ayan  23.0   54322.0      CTO  10864.4  2024-04-23
3    Mk  23.0   42111.0      SDE   8422.2  2024-04-25
4   NaN   NaN       NaN      NaN      NaN  2025-04-12

In [41]:
df.drop(4)

   Name   Age    salary Position    Bonus         DOJ
0  Aman  21.0  150000.0      CEO  30000.0  2024-04-15
1  Atul  22.0   21000.0       HR   4200.0  2024-04-01
2  Ayan  23.0   54322.0      CTO  10864.4  2024-04-23
3    Mk  23.0   42111.0      SDE   8422.2  2024-04-25